/**
 * Golden-path proof loop public content (track 0070 DoD-5).
 *
 * Mirrors the engine single-source narration at:
 *   C:\dev\ledgerful\docs\golden-path.md
 * and CLI `GOLDEN_PATH_CANONICAL_STEPS` (printed on `ledgerful demo --keep`).
 *
 * Timings are pinned only from the track review.md measured on 2026-07-21 —
 * do not invent or average numbers.
 */

/** Canonical argv steps shared with the engine narration (already-installed path). */
export const goldenPathCanonicalSteps = {
  demo: "ledgerful demo --keep --output ./ledgerful-demo",
  cd: "cd ./ledgerful-demo",
  signaturesChain: "ledgerful verify --signatures --chain",
  againstExport:
    "ledgerful verify --signatures --against-export ./ledgerful-DEMO-evidence.zip",
  keepZip: "ledgerful-DEMO-evidence.zip",
} as const;

/** PowerShell copy-paste block — same steps as engine docs/golden-path.md. */
export const goldenPathPowerShell = [
  "ledgerful demo --keep --output .\\ledgerful-demo",
  "Set-Location .\\ledgerful-demo",
  "ledgerful verify --signatures --chain",
  "ledgerful verify --signatures --against-export .\\ledgerful-DEMO-evidence.zip",
].join("\n");

/** Bash copy-paste block — same steps as engine docs/golden-path.md. */
export const goldenPathBash = [
  "ledgerful demo --keep --output ./ledgerful-demo",
  "cd ./ledgerful-demo",
  "ledgerful verify --signatures --chain",
  "ledgerful verify --signatures --against-export ./ledgerful-DEMO-evidence.zip",
].join("\n");

/**
 * Measured timings from conductor/0070-GoldenPathProofLoop/review.md (engine).
 * Environment: Windows x64, 2026-07-21. Never invent; never average T_proof with T_first.
 */
export const goldenPathTimings = {
  measuredOn: "2026-07-21",
  environment: "Windows x64 (host with Scoop + cargo-binstall)",
  tProof: {
    label: "T_proof",
    meaning:
      "Binary already installed → cryptographic VALID + openable DEMO evidence zip",
    shipClaim: "under 3 minutes",
    releaseMedianSeconds: 5.31,
    releaseMaxSeconds: 5.61,
    debugMedianSeconds: 5.67,
    debugMaxSeconds: 5.93,
    note: "Median ≈5–6 s on the measurement host for demo --keep through the CRYPTO VALID beat.",
    remeasureNote:
      "Release median was measured on Scoop ledgerful 0.1.9 on this host; a later release that includes the automated CRYPTO VALID beat should re-measure. Debug path with the beat is still ~5–6 s.",
  },
  tFirst: {
    label: "T_first",
    meaning: "Cold install inclusive (install + T_proof)",
    binstallPlusDemoSeconds: 12.92,
    installSeconds: 6.61,
    demoSeconds: 6.31,
    honestDisclosure:
      "A true stranger cold start (first Scoop/Homebrew, AV scan, slow network, or cargo install from source) can be 1–10+ minutes. Never average into the T_proof claim. Already installed? Start at the demo step.",
  },
} as const;

/** Load-bearing honesty bullets (CLI + web must both say these). */
export const goldenPathHonesty = [
  "Synthetic invoice-service repo generated by ledgerful demo",
  "Disposable keys in the demo dir (not your production ~/.ledgerful/keys/)",
  "Observe mode (warns; does not enforce gate blocks)",
  "Same Ed25519 signatures + chain mechanics as production",
  "Not real business-risk data",
  "The zip is signed evidence only — not a certification or compliance attestation",
] as const;

/** Skeptic exit-criteria checklist. */
export const goldenPathSkepticChecklist = [
  {
    id: "demo-markers",
    label: "[DEMO] markers on demo stdout and DEMO-marked ledger entry summaries",
  },
  {
    id: "valid-chain",
    label:
      "CRYPTO VALID — all signatures + chain verified (automated inside demo)",
  },
  {
    id: "valid-export",
    label: "CRYPTO VALID — live chain head matches retained DEMO export",
  },
  {
    id: "openable-zip",
    label: "An openable zip: ledgerful-DEMO-evidence.zip (kept with --keep)",
  },
  {
    id: "observe-mode",
    label: "Gate mode notice: observe",
  },
  {
    id: "manual-followup",
    label:
      "Follow-up manual verify --signatures --chain / --against-export exit 0",
  },
] as const;

/** What automated demo does (narration only — not a second step script). */
export const goldenPathDemoDoes = [
  "init in observe mode + real hook-driven signed commits (ephemeral demo keypair)",
  "Optional project checks (verify --scope fast) — suite health only, quieted; may WARN/FAIL on synthetic code and is not the brand moment",
  "DEMO evidence zip export",
  "Cryptographic VALID — verify --signatures --chain then --against-export on the automated path",
  "With --keep: repo + zip retained; without --keep: VALID was shown, then cleanup (golden path always uses --keep)",
] as const;

export const goldenPathPage = {
  title: "Golden path — prove it yourself",
  kicker: "Docs · Golden path",
  lead: "Install → signed transaction → cryptographic VALID → openable signed evidence bundle. Be your own auditor in one sitting.",
  successCriterion:
    "Success is a human-visible CRYPTO VALID plus an openable ledgerful-DEMO-evidence.zip — not merely demo exit 0.",
} as const;
